#!/bin/bash

set -e

MANAGE_DIR=$1
VIRTUAL_ENV=$2

MAKE_MIGRATION_OUT=$(
  cd "$MANAGE_DIR" &&
  source "$VIRTUAL_ENV"/bin/activate &&
  ./manage.py makemigrations --dry-run
)

if [[ "$MAKE_MIGRATION_OUT" != "No changes detected" ]]; then
  echo "Migration changes detected."
  echo "$MAKE_MIGRATION_OUT"
  exit 1
fi
