#!/bin/bash

set -e

MANAGE_DIR=$1
VIRTUAL_ENV=$2

if [ -z "$var" ]
then
  MAKE_MIGRATION_OUT=$(
    cd "$MANAGE_DIR" &&
    ./manage.py makemigrations --dry-run
  )
else
  MAKE_MIGRATION_OUT=$(
    cd "$MANAGE_DIR" &&
    source "$HOME/$VIRTUAL_ENV"/bin/activate &&
    ./manage.py makemigrations --dry-run
  )
fi

if [[ "$MAKE_MIGRATION_OUT" != "No changes detected" ]]; then
  echo "Migration changes detected."
  echo "$MAKE_MIGRATION_OUT"
  exit 1
fi
